#!/bin/bash
# Delete all local data
rm -rf ~/data/data_copy/*
# Bring up just Redis
docker-compose up -d redis
# Put now() - 6H in dockets_last_timestamp, documents_last_timestamp, and comments_last_timestamp
python3 set_timestamp.py
docker-compose up -d nginx mongo work_generator work_server dashboard client1